### ISSUE TITLE
Basic usage examples

### ISSUE THREAD

**Issue by andreisusanu** [Shoplo/bonapitit-bonanza-php-sdk#1]
Please add some basic usage examples. Thanks!

**Comment by marrek13** [comment]
Hi, sorry for no answer. I will try to make basic usage examples till the end of the week.

**Comment by marrek13** [comment]
@andreisusanu: please look at the documentation now. Feel free to ask here if you have any more questions!

**Comment by andreisusanu** [comment]
Looks great. Thanks!
